### ISSUE TITLE
Compile to Binary

### ISSUE THREAD

**Issue by DaveDischord** [masutokw/WEMOS-motor-shield-for-stepper-#1]
I've just finished following the How-to [here](https://hackaday.io/project/18439-motor-shield-reprogramming).  How would I compile your firmware to run a stepper motor?

**Comment by masutokw** [comment]
I build the firmware with Code Blocks IDE(code blocks project file is tb6621.cbp)
You must have arm-gcc  and opencm3 libraries  installed.
you should be able to compile it from command without CB 
-------------- Build: Release in tb6621 (compiler: GNU ARM GCC Compiler)---------------

arm-none-eabi-gcc.exe -msoft-float -O1 -Wall -std=c99 -fcommon -mthumb -MD -ffunction-sections -fdata-sections -mcpu=cortex-m0 -DSTM32F0 -IE:\stm32\libopencm3-master\include -IE:\stm32\arm-none-eabi\include -c tb6621.c -o obj\Release\tb6621.o
arm-none-eabi-gcc.exe -msoft-float -O1 -Wall -std=c99 -fcommon -mthumb -MD -ffunction-sections -fdata-sections -mcpu=cortex-m0 -DSTM32F0 -IE:\stm32\libopencm3-master\include -IE:\stm32\arm-none-eabi\include -c usart.c -o obj\Release\usart.o
arm-none-eabi-gcc.exe  -o bin\Release\tb6621.exe obj\Release\tb6621.o obj\Release\usart.o  -Wl,--start-group -lc -lm  -lnosys -Wl,--end-group -LE:/stm32/libopencm3-master/lib -lopencm3_stm32f0 --static -Tstm32f030.ld -nostartfiles -Wl,--gc-sections -mthumb -mcpu=cortex-m0 -msoft-float -Wl,-Map,map.txt -s  
Output file is bin\Release\tb6621.exe with size 129.70 KB
Running project post-build steps
arm-none-eabi-size bin\Release\tb6621.exe
   text	   data	    bss	    dec	    hex	filename
   4632	   1088	    116	   5836	   16cc	bin\Release\tb6621.exe
arm-none-eabi-objcopy bin\Release\tb6621.exe -O ihex bin\Release\tb6621.hex
arm-none-eabi-objcopy bin\Release\tb6621.exe -Obinary bin\Release\tb6621.bin

**Comment by masutokw** [comment]
I will upload  precompiled bin if you wanto check it
you can see it working at https://www.youtube.com/watch?v=7XQXp-VcUK8

**Comment by DaveDischord** [comment]
Oh, that would be awesome!  Thank you

**Comment by masutokw** [comment]
File is   tb6612.bin  or tb6612.hex

**Comment by DaveDischord** [comment]
I just realized that this firmware ran via UART.  Any plans on
incorporating i2C?  I've been comparing your coding with the firmware here
https://hackaday.io/project/18439-motor-shield-reprogramming to see if I
can come up with some way to make it work.

**Comment by masutokw** [comment]
Yes Im working  on it,dc motor-shield firmware use ST device library open source but a very restrictive license.lIbopencm3 version i was using didn´thave support for stm32f0XX, i have upgrade to latest version  
and found they have upgrade it..

**Comment by masutokw** [comment]
Well, I2C code  is almost ready.I will upload in a few days if you are still interested.

**Comment by DaveDischord** [comment]
Absolutely!   Can't wait

**Comment by masutokw** [comment]
I have opened a new repository for I2C version, i haven´t checked with steppers connected because  Im using a hacked shield  (with wire wrapping  soldered on microcontrollers SWD pin for  develop) but I  its responding to master to commands 
Im using a ft260 dongle as PC interface and a FTDI libraries for this chip with delphi IDE but is should work from WEMOS too.
Ask me the details when you decided to check it

https://github.com/masutokw/WEMOS-MOTOR-SHIELD-I2C-STEPPER


![image](https://user-images.githubusercontent.com/10587853/50426673-612c8380-0894-11e9-8b33-6a5a5c77ae73.png)

![image](https://user-images.githubusercontent.com/10587853/50426681-8d480480-0894-11e9-8896-b2b7ba7eff2e.png)
